"""add table translations

Revision ID: 20c9198fc631
Revises: 15e4ddfdfbdd
Create Date: 2024-06-24 13:59:43.802176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20c9198fc631"
down_revision: Union[str, None] = "15e4ddfdfbdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translations",
        sa.Column("translation_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("abbreviation", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("total_books", sa.Integer(), nullable=False),
        sa.Column("total_verses", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("translation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("translations")
    # ### end Alembic commands ###
