"""add table translations

Revision ID: 81b1c93eeacc
Revises: 0b0db323962b
Create Date: 2024-07-31 02:37:36.487824

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81b1c93eeacc"
down_revision: Union[str, None] = "0b0db323962b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translations",
        sa.Column("translation_id", sa.Integer(), nullable=False),
        sa.Column("canon_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("abbreviation", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("total_verses", sa.Integer(), nullable=False),
        sa.Column("hash", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canon_id"],
            ["canons.canon_id"],
        ),
        sa.PrimaryKeyConstraint("translation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("translations")
    # ### end Alembic commands ###
