"""add table verses

Revision ID: a0522eeab268
Revises: 81b1c93eeacc
Create Date: 2024-08-09 09:36:06.613865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a0522eeab268"
down_revision: Union[str, None] = "81b1c93eeacc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("translationId", sa.Integer(), nullable=False),
        sa.Column("bookId", sa.Integer(), nullable=False),
        sa.Column("chapter", sa.Integer(), nullable=False),
        sa.Column("verseNumber", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bookId"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["translationId"],
            ["translations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("verses")
    # ### end Alembic commands ###
