"""add table canons

Revision ID: a1bb2cd33227
Revises: 15e4ddfdfbdd
Create Date: 2024-07-28 21:59:24.677211

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1bb2cd33227"
down_revision: Union[str, None] = "15e4ddfdfbdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canons",
        sa.Column("canon_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("tradition", sa.String(), nullable=False),
        sa.Column("total_books", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("canon_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("canons")
    # ### end Alembic commands ###
