"""add table favorite

Revision ID: d89c65ef679f
Revises: 0054a9df7a2f
Create Date: 2024-08-10 17:43:07.431884

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d89c65ef679f"
down_revision: Union[str, None] = "0054a9df7a2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorites",
        sa.Column("favorites_id", sa.Integer(), nullable=False),
        sa.Column("translation_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("chapter", sa.Integer(), nullable=False),
        sa.Column("verse", sa.Integer(), nullable=False),
        sa.Column("content", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.book_id"],
        ),
        sa.ForeignKeyConstraint(
            ["translation_id"],
            ["translations.translation_id"],
        ),
        sa.PrimaryKeyConstraint("favorites_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("favorites")
    # ### end Alembic commands ###
